# Generated by Django 4.2.29 on 2026-03-17 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('jsm_customer_id', models.CharField(blank=True, max_length=64)),
                ('is_jsm_customer', models.BooleanField(default=False)),
                ('jsm_checked_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MagicLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.portaluser')),
            ],
        ),
        migrations.CreateModel(
            name='DocPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confluence_id', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('rendered_html', models.TextField()),
                ('raw_storage', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('confluence_version', models.IntegerField(default=1)),
                ('space_key', models.CharField(max_length=64)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
                ('search_vector', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='portal.docpage')),
            ],
            options={
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DocImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confluence_id', models.CharField(max_length=256, unique=True)),
                ('local_path', models.CharField(max_length=512)),
                ('original_filename', models.CharField(max_length=256)),
                ('content_type', models.CharField(max_length=64)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portal.docpage')),
            ],
        ),
    ]
