# Generated by Django 4.2.30 on 2026-04-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docpage',
            name='is_folder',
            field=models.BooleanField(default=False),
        ),
    ]
