# Generated by Django 4.2.30 on 2026-05-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_add_is_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=32)),
                ('subject', models.CharField(max_length=512)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='portal_cont_created_9cec38_idx'), models.Index(fields=['status'], name='portal_cont_status_386678_idx')],
            },
        ),
    ]
