# Generated by Django 4.2.30 on 2026-06-08 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_bucket_alter_portaluser_role_sharedfile_fileactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_files', to='portal.portaluser'),
        ),
    ]
