# Generated by Django 4.2.30 on 2026-06-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_sharedfile_processed_sharedfile_processed_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sharedfile',
            index=models.Index(fields=['state', 'processed', 'deleted_at', '-uploaded_at'], name='portal_shar_state_d016cb_idx'),
        ),
    ]
