# Generated by Django 4.2.30 on 2026-06-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_sharedfile_portal_shar_state_d016cb_idx'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bucket',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'general')), fields=('company',), name='uniq_general_bucket_per_company'),
        ),
    ]
