# Generated by Django 4.2.30 on 2026-06-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_bucket_uniq_general_bucket_per_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
