# Generated by Django 4.2.30 on 2026-06-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_seed_demo_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
