# Generated by Django 4.2.30 on 2026-07-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_ticket_ticketmessage_ticketactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='delivery_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='delivery_detail',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='delivery_status',
            field=models.CharField(choices=[('not_applicable', 'Not applicable'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='not_applicable', max_length=16),
        ),
    ]
