# Generated by Django 4.2.30 on 2026-07-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_ticketmessage_delivery_attempted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='esp_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='delivery_status',
            field=models.CharField(choices=[('not_applicable', 'Not applicable'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('failed', 'Failed')], default='not_applicable', max_length=16),
        ),
    ]
