# Generated by Django 4.2.30 on 2026-07-07 19:04
from django.db import migrations, models
import django.db.models.deletion


def move_jira_keys_to_links(apps, schema_editor):
    """Migrate each ticket's single jira_key into a JiraTicketLink row."""
    Ticket = apps.get_model('portal', 'Ticket')
    JiraTicketLink = apps.get_model('portal', 'JiraTicketLink')
    for t in Ticket.objects.exclude(jira_key='').exclude(jira_key=None):
        JiraTicketLink.objects.get_or_create(ticket=t, key=t.jira_key.strip())


def reverse_move(apps, schema_editor):
    """Restore the first link's key back onto Ticket.jira_key (best-effort)."""
    Ticket = apps.get_model('portal', 'Ticket')
    JiraTicketLink = apps.get_model('portal', 'JiraTicketLink')
    for link in JiraTicketLink.objects.all():
        Ticket.objects.filter(pk=link.ticket_id, jira_key='').update(jira_key=link.key[:32])


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_ticketmessage_esp_message_id_and_more'),
    ]

    operations = [
        # Create the link model FIRST so the data move can populate it before
        # the old column is dropped.
        migrations.CreateModel(
            name='JiraTicketLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('cached_status', models.CharField(blank=True, max_length=64)),
                ('cached_status_category', models.CharField(blank=True, max_length=32)),
                ('cached_summary', models.CharField(blank=True, max_length=512)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_links', to='portal.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='jiraticketlink',
            constraint=models.UniqueConstraint(fields=('ticket', 'key'), name='uniq_jira_key_per_ticket'),
        ),
        migrations.RunPython(move_jira_keys_to_links, reverse_move),
        # Drop the old single-key column only after data has moved.
        migrations.RemoveField(
            model_name='ticket',
            name='jira_key',
        ),
    ]
