# Generated by Django 4.2.30 on 2026-07-09 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_remove_ticket_jira_key_jiraticketlink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='portal.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_reads', to='portal.portaluser')),
            ],
            options={
                'unique_together': {('user', 'ticket')},
            },
        ),
    ]
