# Generated by Django 4.2.30 on 2026-07-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_ticketread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='reply_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
