# Generated by Django 4.2.30 on 2026-07-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_alter_ticketmessage_reply_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='jira_comment_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
