# Generated by Django 4.2.30 on 2026-07-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_ticketmessage_jira_comment_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticketmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('jira_comment_id', ''), _negated=True), fields=('ticket', 'jira_comment_id'), name='uniq_jira_comment_per_ticket'),
        ),
    ]
