# Generated by Django 4.2.30 on 2026-08-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_ticketmessage_uniq_jira_comment_per_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_requested', to='portal.portaluser'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='requester_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
