# Generated by Django 4.2.30 on 2026-08-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_ticketmessage_uniq_jira_comment_per_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('standard', 'Standard'), ('csm_direct', 'CSM Direct')], default='standard', max_length=16),
        ),
    ]
