# Generated by Django 4.2.30 on 2026-08-05 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # Two branches both numbered 0024 landed independently — requester (this
    # branch) and priority (PR #40). Depending on both collapses them to a
    # single leaf without renaming either file, so a database that already
    # applied one of them stays valid.
    dependencies = [
        ('portal', '0024_ticket_requester_ticket_requester_email'),
        ('portal', '0024_ticket_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to='portal.portaluser'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='tickets_watching', to='portal.portaluser'),
        ),
    ]
