# Generated by Django 4.2.30 on 2026-08-05 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_ticket_requester_ticket_requester_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to='portal.portaluser'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='tickets_watching', to='portal.portaluser'),
        ),
    ]
