# Generated by Django 4.2.30 on 2026-08-07 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_ticket_assignee_ticket_watchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_buckets', to='portal.portaluser'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='portal.bucket'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='kind',
            field=models.CharField(choices=[('request', 'Request'), ('general', 'General'), ('folder', 'Folder')], default='general', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='bucket',
            constraint=models.CheckConstraint(check=models.Q(('parent__isnull', True), ('kind', 'folder'), _connector='OR'), name='only_folders_may_be_nested'),
        ),
    ]
