# Generated by Django 4.2.30 on 2026-08-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_bucket_created_by_bucket_parent_alter_bucket_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
