# Generated by Django 4.2.30 on 2026-08-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_apiclient'),
        ('portal', '0027_bucket_required'),
    ]

    operations = [
    ]
