# Generated by Django 4.2.30 on 2026-08-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_backfill_first_response_at'),
        ('portal', '0028_merge_0025_apiclient_0027_bucket_required'),
    ]

    operations = [
    ]
