# Generated by Django 4.2.30 on 2026-08-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_sitenotice_noticedismissal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiclient',
            name='can_provision',
            field=models.BooleanField(default=False, help_text='Allow this client to POST to /api/v1/provisioning/ (create companies and portal users).'),
        ),
    ]
