# Generated by Django 4.2.30 on 2026-08-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_apiclient_can_provision'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='upload_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
