# Generated by Django 4.2.30 on 2026-08-21 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_sharedfile_upload_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='origin',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'CiteMed')], default='customer', max_length=16),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='external_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='item_type',
            field=models.CharField(choices=[('file', 'File'), ('link', 'Link')], default='file', max_length=8),
        ),
        migrations.CreateModel(
            name='ShareNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('first_opened_at', models.DateTimeField(blank=True, null=True)),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.IntegerField(default=0)),
                ('remind', models.BooleanField(default=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='portal.bucket')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='portal.sharedfile')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_notices', to='portal.portaluser')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_share_notices', to='portal.portaluser')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['first_opened_at', 'remind', 'reminder_count', 'sent_at'], name='portal_shar_first_o_2cf2ee_idx'), models.Index(fields=['bucket', 'recipient'], name='portal_shar_bucket__8bddbc_idx')],
            },
        ),
    ]
