# Generated by Django 4.2.30 on 2026-08-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_bucket_origin_sharedfile_external_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharenotice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
