# Generated by Django 4.2.30 on 2026-09-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_sharenotice_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharenotice',
            name='last_email_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
