# Generated by Django 4.2.30 on 2026-09-08 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_sharedfile_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='licensed_modules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to customer'), ('submitted', 'Submitted by customer'), ('closed', 'Closed')], db_index=True, default='draft', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to='portal.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_requests_created', to='portal.portaluser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RosterImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('state', models.CharField(choices=[('pending_review', 'Waiting for the uploader to confirm'), ('confirmed', 'Confirmed, waiting to be applied'), ('applying', 'Being applied'), ('done', 'Applied'), ('failed', 'Failed')], db_index=True, default='pending_review', max_length=16)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('problems', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='portal.userrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_imports', to='portal.portaluser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('modules', models.JSONField(blank=True, default=list)),
                ('role_type', models.CharField(choices=[('admin', 'Admin'), ('fulfiller', 'Fulfiller / Edit'), ('viewer', 'Viewer')], default='viewer', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('form', 'Typed into the form'), ('import', 'Imported from a file')], default='form', max_length=8)),
                ('added_at', models.DateTimeField(blank=True, null=True)),
                ('activation_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('status_note', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portal_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_from', to='portal.portaluser')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='portal.userrequest')),
                ('status_overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_overrides', to='portal.portaluser')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'email'],
            },
        ),
        migrations.AddConstraint(
            model_name='requesteduser',
            constraint=models.UniqueConstraint(fields=('request', 'email'), name='uniq_requested_email_per_request'),
        ),
    ]
